In [1]:
import os
import matplotlib.pyplot as plt
import joblib    #for saving the file
import numpy as np

plt.style.use("fivethirtyeight")

In [2]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None) :
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def fit(self, X, y) :
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        

In [8]:
obj = Perceptron(eta = 0.01, epochs=10)

In [20]:
obj.eta

0.01

In [12]:
obj.epochs

10

In [11]:
obj.weights

array([ 1.08323437e-05, -1.35835875e-04,  1.54070410e-05])

In [3]:
X = np.ones((4,2))
y= np.ones((4,1))

In [13]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
